version: "3"
services:
  api:
    container_name: api
    build: ./back
    ports:
      - "8080:8080"
    working_dir: /back
    tty: true
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    container_name: db
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: ichimon
    restart: always
