version: "3"
services:
  api:
    build: ./back
    ports:
      - "8080:8080"
    working_dir: /back
    tty: true
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: ichimon
    restart: always
    networks:
      - lesson
networks:
  lesson:
